// Textos de la ticketera rediseñada que no existen en lib/i18n.tsx.
// Los textos que ya existían ahí (home.search, home.time.*, home.loading, home.pastEvent,
// menu.*) se siguen leyendo de ese diccionario.
import type { Lang } from '@/lib/i18n'

const es = {
  'ev.skip': 'Saltar al contenido',
  'ev.brand': 'Sivar Eventos — Inicio',
  'ev.home': 'Inicio',
  'ev.homeAria': 'Inicio',
  'ev.searchLabel': 'Buscar eventos, artistas o venues',
  'ev.langNav': 'Idioma',
  'ev.signIn': 'Entrar',
  'ev.social.instagram': 'Instagram de Sivar Music',
  'ev.social.spotify': 'Spotify de Sivar Music',
  'ev.social.youtube': 'YouTube de Sivar Music',
  'ev.eyebrow': 'El Salvador · En vivo',
  'ev.title': 'Cartelera',
  'ev.filterLabel': 'Filtrar por fecha',
  'ev.filterAll': 'Todos',
  'ev.howto': 'Así se compra',
  'ev.how1.title': 'Elegí y dejá tus datos',
  'ev.how1.text': 'Te damos un código de orden.',
  'ev.how2.title': 'Transferí con tu código',
  'ev.how2.text': 'Como concepto, desde tu banco.',
  'ev.how3.title': 'Subí el comprobante',
  'ev.how3.text': 'Y te llegan las entradas con QR.',
  'ev.next': 'Próximo',
  'ev.nextEvent': 'Próximo evento',
  'ev.seeTickets': 'Ver entradas',
  'ev.moreDates': 'Más fechas',
  'ev.poster': 'Afiche de {name}',
  'ev.posterNone': '{name} (sin afiche)',
  'ev.posterTag': 'Sivar Music · En vivo',
  'ev.price': 'Precio ',
  'ev.loading': 'Cargando eventos…',
  'ev.empty.24h': 'Nada en las próximas 24 horas',
  'ev.empty.7d': 'Nada en los próximos 7 días',
  'ev.empty.30d': 'Nada en los próximos 30 días',
  'ev.empty.none': 'Todavía no hay eventos',
  'ev.empty.text': 'No hay eventos en este período. Probá con un rango más amplio.',
  'ev.empty.noneText': 'Volvé pronto: estamos preparando la cartelera.',
  'ev.see30': 'Ver 30 días',
  'ev.seeAll': 'Ver todos los eventos',
  'ev.noResults': 'Sin resultados para “{q}”',
  'ev.noResultsText': 'Revisá cómo lo escribiste o buscá por artista o venue.',
  'ev.clearSearch': 'Limpiar búsqueda',
  'ev.errorTitle': 'No pudimos cargar la cartelera',
  'ev.errorText': 'Revisá tu conexión e intentá de nuevo.',
  'ev.retry': 'Reintentar',
  'ev.footerNav': 'Enlaces del pie',
  'ev.forArtists': 'Sivar Events for Artists',
  'ev.privacy': 'Políticas de privacidad',
  'ev.footerNote': 'Sivar Music Group · El Salvador · Precios en USD',
} as const

export type CopyKey = keyof typeof es

const en: Record<CopyKey, string> = {
  'ev.skip': 'Skip to content',
  'ev.brand': 'Sivar Eventos — Home',
  'ev.home': 'Home',
  'ev.homeAria': 'Home',
  'ev.searchLabel': 'Search events, artists or venues',
  'ev.langNav': 'Language',
  'ev.signIn': 'Sign in',
  'ev.social.instagram': 'Sivar Music on Instagram',
  'ev.social.spotify': 'Sivar Music on Spotify',
  'ev.social.youtube': 'Sivar Music on YouTube',
  'ev.eyebrow': 'El Salvador · Live',
  'ev.title': "What's on",
  'ev.filterLabel': 'Filter by date',
  'ev.filterAll': 'All',
  'ev.howto': 'How to buy',
  'ev.how1.title': 'Pick and leave your details',
  'ev.how1.text': 'We give you an order code.',
  'ev.how2.title': 'Transfer with your code',
  'ev.how2.text': 'As the concept, from your bank.',
  'ev.how3.title': 'Upload the receipt',
  'ev.how3.text': 'And your tickets with QR arrive.',
  'ev.next': 'Next',
  'ev.nextEvent': 'Next event',
  'ev.seeTickets': 'See tickets',
  'ev.moreDates': 'More dates',
  'ev.poster': 'Poster for {name}',
  'ev.posterNone': '{name} (no poster)',
  'ev.posterTag': 'Sivar Music · Live',
  'ev.price': 'Price ',
  'ev.loading': 'Loading events…',
  'ev.empty.24h': 'Nothing in the next 24 hours',
  'ev.empty.7d': 'Nothing in the next 7 days',
  'ev.empty.30d': 'Nothing in the next 30 days',
  'ev.empty.none': 'No events yet',
  'ev.empty.text': 'No events in this period. Try a wider range.',
  'ev.empty.noneText': 'Check back soon: we are putting the lineup together.',
  'ev.see30': 'See 30 days',
  'ev.seeAll': 'See all events',
  'ev.noResults': 'No results for “{q}”',
  'ev.noResultsText': 'Check the spelling or search by artist or venue.',
  'ev.clearSearch': 'Clear search',
  'ev.errorTitle': "We couldn't load the lineup",
  'ev.errorText': 'Check your connection and try again.',
  'ev.retry': 'Try again',
  'ev.footerNav': 'Footer links',
  'ev.forArtists': 'Sivar Events for Artists',
  'ev.privacy': 'Privacy policy',
  'ev.footerNote': 'Sivar Music Group · El Salvador · Prices in USD',
}

const DICTS: Record<Lang, Record<CopyKey, string>> = { es, en }

export function copyFor(lang: Lang, key: CopyKey, vars?: Record<string, string | number>): string {
  let text = DICTS[lang][key]
  if (vars) for (const [k, v] of Object.entries(vars)) text = text.replaceAll(`{${k}}`, String(v))
  return text
}
