// Textos de la ticketera rediseñada que no existen en lib/i18n.tsx.
// Los textos que ya existían ahí (home.search, home.time.*, home.loading, home.pastEvent,
// menu.*) se siguen leyendo de ese diccionario.
import type { Lang } from '@/lib/i18n'

const es = {
  'ev.skip': 'Saltar al contenido',
  'ev.brand': 'Sivar Eventos — Inicio',
  'ev.home': 'Inicio',
  'ev.homeAria': 'Inicio',
  'ev.searchLabel': 'Buscar eventos, artistas o venues',
  'ev.langNav': 'Idioma',
  'ev.signIn': 'Entrar',
  'ev.social.instagram': 'Instagram de Sivar Music',
  'ev.social.spotify': 'Spotify de Sivar Music',
  'ev.social.youtube': 'YouTube de Sivar Music',
  'ev.eyebrow': 'El Salvador · En vivo',
  'ev.title': 'Cartelera',
  'ev.filterLabel': 'Filtrar por fecha',
  'ev.filterAll': 'Todos',
  'ev.howto': 'Así se compra',
  'ev.how1.title': 'Elegí y dejá tus datos',
  'ev.how1.text': 'Te damos un código de orden.',
  'ev.how2.title': 'Transferí con tu código',
  'ev.how2.text': 'Como concepto, desde tu banco.',
  'ev.how3.title': 'Subí el comprobante',
  'ev.how3.text': 'Y te llegan las entradas con QR.',
  'ev.next': 'Próximo',
  'ev.nextEvent': 'Próximo evento',
  'ev.seeTickets': 'Ver entradas',
  'ev.moreDates': 'Más fechas',
  'ev.poster': 'Afiche de {name}',
  'ev.posterNone': '{name} (sin afiche)',
  'ev.posterTag': 'Sivar Music · En vivo',
  'ev.price': 'Precio ',
  'ev.loading': 'Cargando eventos…',
  'ev.empty.24h': 'Nada en las próximas 24 horas',
  'ev.empty.7d': 'Nada en los próximos 7 días',
  'ev.empty.30d': 'Nada en los próximos 30 días',
  'ev.empty.none': 'Todavía no hay eventos',
  'ev.empty.text': 'No hay eventos en este período. Probá con un rango más amplio.',
  'ev.empty.noneText': 'Volvé pronto: estamos preparando la cartelera.',
  'ev.see30': 'Ver 30 días',
  'ev.seeAll': 'Ver todos los eventos',
  'ev.noResults': 'Sin resultados para “{q}”',
  'ev.noResultsText': 'Revisá cómo lo escribiste o buscá por artista o venue.',
  'ev.clearSearch': 'Limpiar búsqueda',
  'ev.errorTitle': 'No pudimos cargar la cartelera',
  'ev.errorText': 'Revisá tu conexión e intentá de nuevo.',
  'ev.retry': 'Reintentar',
  'ev.footerNav': 'Enlaces del pie',
  'ev.forArtists': 'Sivar Events for Artists',
  'ev.privacy': 'Políticas de privacidad',
  'ev.footerNote': 'Sivar Music Group · El Salvador · Precios en USD',
  // ── Fase 2: flujo del comprador ──
  'evs.stepsLabel': 'Pasos de la compra',
  'evs.step1': 'Datos',
  'evs.step2': 'Pago',
  'evs.step3': 'Confirmación',
  'evs.status.pending': 'Pendiente de comprobante',
  'evs.status.missing': 'Falta comprobante',
  'evs.status.review': 'En revisión',
  'evs.status.confirmed': 'Confirmada',
  'evs.status.rejected': 'Rechazada',
  'evd.presents': 'Sivar Music presenta',
  'evd.factDate': 'Fecha',
  'evd.factPlace': 'Lugar',
  'evd.factPrice': 'Precio',
  'evd.factArtists': 'Artistas',
  'evd.showAt': 'Show {time}',
  'evd.seeMap': 'Ver en el mapa',
  'evd.about': 'Sobre el evento',
  'evd.tickets': 'Entradas',
  'evd.available': 'Disponible',
  'evd.fewLeft': 'Quedan {n}',
  'evd.fewLeftLong': 'Quedan {n} entradas',
  'evd.each': 'c/u',
  'evd.qty': 'Cantidad',
  'evd.qtyDec': 'Quitar una entrada',
  'evd.qtyInc': 'Agregar una entrada',
  'evd.qtyInput': 'Cantidad de entradas',
  'evd.noCard': 'Sin tarjeta: pagás por transferencia bancaria.',
  'evd.onlyLeft': 'Solo quedan {n} entradas',
  'evd.buyRegion': 'Comprar entradas',
  'evd.soldOut': 'Agotado',
  'evd.soldOutText': 'Se vendieron todas las entradas. Seguí a Sivar Music para enterarte de nuevas fechas.',
  'evd.followIg': 'Seguir en Instagram',
  'evd.how1.title': 'Elegís cuántas y dejás tus datos',
  'evd.how1.text': 'Te damos un código de orden.',
  'evd.how2.title': 'Transferís usando el código como concepto',
  'evd.how2.text': 'Desde la app de tu banco.',
  'evd.how3.title': 'Subís el comprobante',
  'evd.how3.text': 'Imagen o PDF de hasta 4 MB.',
  'evd.how4.title': 'Te llegan tus entradas con QR',
  'evd.how4.text': 'Por correo, cuando el equipo confirma el pago.',
  'evd.mapTitle': 'Mapa — {venue}',
  'evc.title': 'Tus datos',
  'evc.lead': 'Con esto armamos tu orden y te enviamos las entradas.',
  'evc.summary': 'Resumen',
  'evc.qty': 'Cantidad',
  'evc.reviewOne': 'Revisá 1 campo',
  'evc.reviewMany': 'Revisá {n} campos',
  'evc.reviewText': 'Te marcamos abajo qué falta.',
  'evc.stockTitle': 'No quedan entradas disponibles para {n}',
  'evc.stockText': 'Alguien compró antes que vos. Todavía quedan {left}.',
  'evc.buyN': 'Comprar {n}',
  'evc.otherEvents': 'Ver otros eventos',
  'evc.phoneHint': 'Te contactamos por aquí si hay algún problema con tu pago.',
  'evc.phoneActive': 'Ya hay una solicitud activa con este teléfono.',
  'evc.fromAccount': 'De tu cuenta',
  'evc.emailHint': 'Usamos el correo de tu cuenta. Tus entradas también quedan en {account}.',
  'evc.myAccount': 'Mi cuenta',
  'evc.activeTitle': '¿Ya empezaste una compra?',
  'evc.activeText': 'Buscá el correo con tu código de orden y terminá el pago desde ahí. Si fue un error, escribinos y la liberamos.',
  'evc.continue': 'Continuar al pago',
  'evc.generating': 'Generando tu código…',
  'evc.generatingStatus': 'Generando tu código de orden…',
  'evp.title': 'Transferí y subí tu comprobante',
  'evp.codeHint': 'Escribilo como {concept} de la transferencia. Sin este código no podemos encontrar tu pago.',
  'evp.copyCode': 'Copiar código',
  'evp.saveLink': 'Guardá este link para volver a subir el comprobante.',
  'evp.step1': 'Transferí {amount}',
  'evp.step1NoAmount': 'Transferí',
  'evp.step2': 'Subí el comprobante',
  'evp.conceptRequired': 'Concepto · obligatorio',
  'evp.exactAmount': 'Monto exacto',
  'evp.copyAccount': 'Copiar número de cuenta',
  'evp.copyConcept': 'Copiar concepto',
  'evp.copyAmount': 'Copiar monto',
  'evp.qrTitle': 'Pagar con el QR del banco',
  'evp.qrHint': 'Opcional. Escanealo desde la app de tu banco. Igual escribí {code} como concepto.',
  'evp.errSize': 'Pesa {size} MB. El máximo es {max} MB.',
  'evp.removeFile': 'Quitar archivo',
  'evp.uploading': 'Subiendo comprobante',
  'evp.ready': 'listo para enviar',
  'evp.drop': 'Soltalo acá',
  'evp.chooseOther': 'Elegí otro archivo',
  'evp.uploadHint': 'Una captura o el PDF que te da tu banco',
  'evp.networkTitle': 'Se cortó la subida',
  'evp.networkText': 'Revisá tu conexión. Tu orden sigue reservada.',
  'evp.retry': 'Reintentar',
  'evp.sending': 'Enviando…',
  'evp.dontClose': 'No cierres esta página hasta que termine.',
  'evp.rejectedTitle': 'No pudimos confirmar tu pago',
  'evp.rejectedLead': 'El equipo revisó el comprobante de la orden {code} y no pudo validarlo.',
  'evp.rejectedWhen': 'Suele pasar cuando…',
  'evp.rejectedAmount': 'el monto transferido no es {amount},',
  'evp.rejectedConcept': 'el concepto no dice {code},',
  'evp.rejectedImage': 'o la imagen no se lee bien.',
  'evp.helpTitle': 'Escribinos con tu código de orden',
  'evp.helpText': 'Si ya transferiste, lo resolvemos. Tené a mano el comprobante.',
  'evp.helpEmail': 'Correo',
  'evp.reupload': 'Subir otro comprobante',
  'evg.stamp': 'Recibido',
  'evg.titleA': '¡Ya casi!',
  'evg.titleB': 'Comprobante recibido',
  'evg.paid': 'Pagada',
  'evg.totalPaid': 'Total pagado',
  'evg.totalTransferred': 'Total transferido',
  'evg.status': 'Estado',
  'evg.nextTitle': 'Qué pasa ahora',
  'evg.next1': 'Revisamos tu transferencia',
  'evg.next2': 'Te llegan las entradas con QR',
  'evg.next3': 'Mostrás el QR en la puerta',
  'evg.next3Text': 'Desde el celular, con el brillo alto.',
  'evg.noMailTitle': '¿No te llegó el correo?',
  'evg.noMailText': 'Revisá spam o promociones. Si iniciás sesión con ese correo, también las ves en Mi cuenta.',
  'evg.helpTitle': '¿Algo no cuadra?',
  'evg.helpText': 'Escribinos con tu código',
  'evg.backToLineup': 'Volver a la cartelera',
  'eva.emptyText': 'Si compraste sin iniciar sesión, tus entradas llegaron a tu correo.',
  'eva.seeLineup': 'Ver la cartelera',
  'eva.myTickets': 'Mis entradas',
  'eva.showAtDoor': 'Mostralo en la puerta con el brillo alto.',
  'eva.orderLine': 'Orden {code} · {tickets}',
  'eva.qrAfterReview': 'Tu QR aparece cuando el equipo confirme el pago.',
  'eva.seePayment': 'Ver estado del pago',
  'eva.uploadProof': 'Subir comprobante',
  'eva.rejectedLine': 'No pudimos confirmar el pago de la orden {code}.',
  'eva.seeWhatHappened': 'Ver qué pasó',
  'eva.brand': 'Sivar Eventos',
  'eva.access': 'Acceso',
  'eva.invalidHint': 'Revisalos o usá “Olvidé mi contraseña”.',
  'eva.pwShort': 'Tiene {n} caracteres. Necesita al menos {min}.',
  'eva.showPw': 'Mostrar contraseña',
  'eva.hidePw': 'Ocultar contraseña',
} as const

export type CopyKey = keyof typeof es

const en: Record<CopyKey, string> = {
  'ev.skip': 'Skip to content',
  'ev.brand': 'Sivar Eventos — Home',
  'ev.home': 'Home',
  'ev.homeAria': 'Home',
  'ev.searchLabel': 'Search events, artists or venues',
  'ev.langNav': 'Language',
  'ev.signIn': 'Sign in',
  'ev.social.instagram': 'Sivar Music on Instagram',
  'ev.social.spotify': 'Sivar Music on Spotify',
  'ev.social.youtube': 'Sivar Music on YouTube',
  'ev.eyebrow': 'El Salvador · Live',
  'ev.title': "What's on",
  'ev.filterLabel': 'Filter by date',
  'ev.filterAll': 'All',
  'ev.howto': 'How to buy',
  'ev.how1.title': 'Pick and leave your details',
  'ev.how1.text': 'We give you an order code.',
  'ev.how2.title': 'Transfer with your code',
  'ev.how2.text': 'As the concept, from your bank.',
  'ev.how3.title': 'Upload the receipt',
  'ev.how3.text': 'And your tickets with QR arrive.',
  'ev.next': 'Next',
  'ev.nextEvent': 'Next event',
  'ev.seeTickets': 'See tickets',
  'ev.moreDates': 'More dates',
  'ev.poster': 'Poster for {name}',
  'ev.posterNone': '{name} (no poster)',
  'ev.posterTag': 'Sivar Music · Live',
  'ev.price': 'Price ',
  'ev.loading': 'Loading events…',
  'ev.empty.24h': 'Nothing in the next 24 hours',
  'ev.empty.7d': 'Nothing in the next 7 days',
  'ev.empty.30d': 'Nothing in the next 30 days',
  'ev.empty.none': 'No events yet',
  'ev.empty.text': 'No events in this period. Try a wider range.',
  'ev.empty.noneText': 'Check back soon: we are putting the lineup together.',
  'ev.see30': 'See 30 days',
  'ev.seeAll': 'See all events',
  'ev.noResults': 'No results for “{q}”',
  'ev.noResultsText': 'Check the spelling or search by artist or venue.',
  'ev.clearSearch': 'Clear search',
  'ev.errorTitle': "We couldn't load the lineup",
  'ev.errorText': 'Check your connection and try again.',
  'ev.retry': 'Try again',
  'ev.footerNav': 'Footer links',
  'ev.forArtists': 'Sivar Events for Artists',
  'ev.privacy': 'Privacy policy',
  'ev.footerNote': 'Sivar Music Group · El Salvador · Prices in USD',
  // ── Phase 2: buyer flow ──
  'evs.stepsLabel': 'Purchase steps',
  'evs.step1': 'Details',
  'evs.step2': 'Payment',
  'evs.step3': 'Confirmation',
  'evs.status.pending': 'Receipt pending',
  'evs.status.missing': 'Receipt missing',
  'evs.status.review': 'Under review',
  'evs.status.confirmed': 'Confirmed',
  'evs.status.rejected': 'Rejected',
  'evd.presents': 'Sivar Music presents',
  'evd.factDate': 'Date',
  'evd.factPlace': 'Place',
  'evd.factPrice': 'Price',
  'evd.factArtists': 'Artists',
  'evd.showAt': 'Show {time}',
  'evd.seeMap': 'See on the map',
  'evd.about': 'About the event',
  'evd.tickets': 'Tickets',
  'evd.available': 'Available',
  'evd.fewLeft': '{n} left',
  'evd.fewLeftLong': '{n} tickets left',
  'evd.each': 'each',
  'evd.qty': 'Quantity',
  'evd.qtyDec': 'Remove one ticket',
  'evd.qtyInc': 'Add one ticket',
  'evd.qtyInput': 'Number of tickets',
  'evd.noCard': 'No card needed: you pay by bank transfer.',
  'evd.onlyLeft': 'Only {n} tickets left',
  'evd.buyRegion': 'Buy tickets',
  'evd.soldOut': 'Sold out',
  'evd.soldOutText': 'All tickets have been sold. Follow Sivar Music to hear about new dates.',
  'evd.followIg': 'Follow on Instagram',
  'evd.how1.title': 'Choose how many and leave your details',
  'evd.how1.text': 'We give you an order code.',
  'evd.how2.title': 'Transfer using the code as the reference',
  'evd.how2.text': 'From your bank app.',
  'evd.how3.title': 'Upload the receipt',
  'evd.how3.text': 'Image or PDF up to 4 MB.',
  'evd.how4.title': 'Your tickets with QR arrive',
  'evd.how4.text': 'By email, once the team confirms the payment.',
  'evd.mapTitle': 'Map — {venue}',
  'evc.title': 'Your details',
  'evc.lead': 'With this we build your order and send you the tickets.',
  'evc.summary': 'Summary',
  'evc.qty': 'Quantity',
  'evc.reviewOne': 'Check 1 field',
  'evc.reviewMany': 'Check {n} fields',
  'evc.reviewText': 'We marked below what is missing.',
  'evc.stockTitle': 'There are not enough tickets left for {n}',
  'evc.stockText': 'Someone bought before you. There are still {left} left.',
  'evc.buyN': 'Buy {n}',
  'evc.otherEvents': 'See other events',
  'evc.phoneHint': 'We contact you here if there is a problem with your payment.',
  'evc.phoneActive': 'There is already an active request with this phone number.',
  'evc.fromAccount': 'From your account',
  'evc.emailHint': 'We use your account email. Your tickets are also saved in {account}.',
  'evc.myAccount': 'My account',
  'evc.activeTitle': 'Did you already start a purchase?',
  'evc.activeText': 'Look for the email with your order code and finish the payment from there. If it was a mistake, write to us and we will release it.',
  'evc.continue': 'Continue to payment',
  'evc.generating': 'Generating your code…',
  'evc.generatingStatus': 'Generating your order code…',
  'evp.title': 'Transfer and upload your receipt',
  'evp.codeHint': 'Write it as the {concept} of the transfer. Without this code we cannot find your payment.',
  'evp.copyCode': 'Copy code',
  'evp.saveLink': 'Save this link to upload the receipt again later.',
  'evp.step1': 'Transfer {amount}',
  'evp.step1NoAmount': 'Transfer',
  'evp.step2': 'Upload the receipt',
  'evp.conceptRequired': 'Reference · required',
  'evp.exactAmount': 'Exact amount',
  'evp.copyAccount': 'Copy account number',
  'evp.copyConcept': 'Copy reference',
  'evp.copyAmount': 'Copy amount',
  'evp.qrTitle': 'Pay with the bank QR',
  'evp.qrHint': 'Optional. Scan it from your bank app. Still write {code} as the reference.',
  'evp.errSize': 'It weighs {size} MB. The maximum is {max} MB.',
  'evp.removeFile': 'Remove file',
  'evp.uploading': 'Uploading receipt',
  'evp.ready': 'ready to send',
  'evp.drop': 'Drop it here',
  'evp.chooseOther': 'Choose another file',
  'evp.uploadHint': 'A screenshot or the PDF from your bank',
  'evp.networkTitle': 'The upload was interrupted',
  'evp.networkText': 'Check your connection. Your order is still reserved.',
  'evp.retry': 'Try again',
  'evp.sending': 'Sending…',
  'evp.dontClose': 'Do not close this page until it finishes.',
  'evp.rejectedTitle': "We couldn't confirm your payment",
  'evp.rejectedLead': "The team reviewed the receipt for order {code} and couldn't validate it.",
  'evp.rejectedWhen': 'This usually happens when…',
  'evp.rejectedAmount': 'the amount transferred is not {amount},',
  'evp.rejectedConcept': 'the reference does not say {code},',
  'evp.rejectedImage': 'or the image is hard to read.',
  'evp.helpTitle': 'Write to us with your order code',
  'evp.helpText': 'If you already transferred, we will sort it out. Keep the receipt at hand.',
  'evp.helpEmail': 'Email',
  'evp.reupload': 'Upload another receipt',
  'evg.stamp': 'Received',
  'evg.titleA': 'Almost there!',
  'evg.titleB': 'Receipt received',
  'evg.paid': 'Paid',
  'evg.totalPaid': 'Total paid',
  'evg.totalTransferred': 'Total transferred',
  'evg.status': 'Status',
  'evg.nextTitle': 'What happens now',
  'evg.next1': 'We review your transfer',
  'evg.next2': 'Your tickets with QR arrive',
  'evg.next3': 'Show the QR at the door',
  'evg.next3Text': 'From your phone, with the brightness up.',
  'evg.noMailTitle': "Didn't get the email?",
  'evg.noMailText': 'Check spam or promotions. If you sign in with that email, you also see them in My account.',
  'evg.helpTitle': "Something doesn't add up?",
  'evg.helpText': 'Write to us with your code',
  'evg.backToLineup': 'Back to the lineup',
  'eva.emptyText': 'If you bought without signing in, your tickets were sent to your email.',
  'eva.seeLineup': 'See the lineup',
  'eva.myTickets': 'My tickets',
  'eva.showAtDoor': 'Show it at the door with the brightness up.',
  'eva.orderLine': 'Order {code} · {tickets}',
  'eva.qrAfterReview': 'Your QR appears once the team confirms the payment.',
  'eva.seePayment': 'See payment status',
  'eva.uploadProof': 'Upload receipt',
  'eva.rejectedLine': "We couldn't confirm the payment for order {code}.",
  'eva.seeWhatHappened': 'See what happened',
  'eva.brand': 'Sivar Eventos',
  'eva.access': 'Access',
  'eva.invalidHint': 'Check them or use “Forgot my password”.',
  'eva.pwShort': 'It has {n} characters. It needs at least {min}.',
  'eva.showPw': 'Show password',
  'eva.hidePw': 'Hide password',
}

const DICTS: Record<Lang, Record<CopyKey, string>> = { es, en }

export function copyFor(lang: Lang, key: CopyKey, vars?: Record<string, string | number>): string {
  let text = DICTS[lang][key]
  if (vars) for (const [k, v] of Object.entries(vars)) text = text.replaceAll(`{${k}}`, String(v))
  return text
}
